name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install backend dependencies
      run: |
        npm ci || cat /home/runner/.npm/_logs/*-debug.log
      working-directory: backend
      

    - name: Test backend
      run: npm test
      working-directory: backend

    - name: Install frontend dependencies
      run: npm ci
      working-directory: frontend

    - name: Test frontend
      run: npm test
      working-directory: frontend

